openapi: 3.0.0
info:
  version: 0.9.0
  title: Policendaten Schadenmeldung API
  description: |
    🇩🇪 Diese API liefert Policendaten basierend auf dem Ereignis-Datum für eine Schadenmeldung.

    🇬🇧 This API provides policy data based on the event date for an accident report.
  license:
    name: Apache License 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: FIXME

paths:
  /policy:
    get:
      description: |
        🇩🇪 Liefert eine Liste von Subnummern basierend auf dem Ereignis-Datum und optional der Suva KundenNr. 
        Falls keine KundenNr angegeben wird, wird die Authentifizierung zur Identifikation des Kunden verwendet.

        🇬🇧 Provides a list of subnumbers based on the event date and optionally the Suva customer ID. 
        If no customer ID is specified, authentication will identify the customer.
      tags:
        - Policendaten
      operationId: getPolicy
      parameters:
        - name: eventDate
          in: query
          required: true
          description: |
            🇩🇪 Das Datum des Unfall-Ereignisses. Wenn das aktuelle Tagesdatum verwendet wird, muss die Schnittstelle
            später erneut mit dem Ereignis-Datum des Schadens aufgerufen werden, insbesondere bei einem Jahreswechsel,
            um sicherzustellen, dass die in der Schadenmeldung referenzierten Objekte zum Ereignis-Datum gültig sind.
            **Einschränkung:** Datum muss <= Tagesdatum sein und nicht weiter zurück als das vorhergehende Kalenderjahr.

            🇬🇧 The event date. If the current date is used, the API should later be called again
            with the accident event date, particularly if a year change occurs in between,
            to ensure objects referenced in the accident report are valid at the event date.
            **Restriction:** The date must be <= today's date and no earlier than the previous calendar year.
          schema:
            type: string
            format: date
        - name: customerID
          in: query
          required: false
          description: |
            🇩🇪 Die Suva-Kundennummer (z.B. 8-01747-90000).

            🇬🇧 Suva customer ID (e.g., 8-01747-90000).
          schema:
            type: string
        - $ref: "#/components/parameters/X-Client-Vendor"
        - $ref: "#/components/parameters/X-Client-Name"
        - $ref: "#/components/parameters/X-Client-Version"
      security:
        # 🇩🇪 entweder mit API-Key oder anonym - im Fall von anonymem Zugriff werden nicht alle Daten geliefert.
        #       
        # 🇬🇧 Access can be anonymous, but API-key usage is recommended as anonymous access may limit data retrieval.
        #
        - [] # anonymous
        - ApiKeyAuth: [] 
      responses:
        200:
          description: |
            🇩🇪 Liste von Subnummern der Police.

            🇬🇧 List of policy subnumbers.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Subnummer"
        401:
          description: |
            🇩🇪 Ungültige Authentifizierung oder Daten mit der Authentifizierung nicht zugänglich.

            🇬🇧 Invalid authentication or inaccessible data for the provided authentication.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        400:
          description: |
            🇩🇪 Anfrage konnte nicht verarbeitet werden.

            🇬🇧 The request could not be processed due to an error.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /policy/{language}/{gender}:
    get:
      description: |
        🇩🇪 Liefert eine gefilterte Liste von Subnummern basierend auf Sprache und Geschlecht.

        🇬🇧 Provides a filtered list of subnumbers based on language and gender.
      tags:
        - Policendaten
      operationId: getPolicyFiltered
      parameters:
        - name: language
          in: path
          required: true
          schema:
            type: string
            enum: [de, fr, it, en]
          description: |
            🇩🇪 Gewünschte Sprache für die Berufsbezeichnungen.

            🇬🇧 Desired language for occupation descriptions.
        - name: gender
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/Gender"
          description: |
            🇩🇪 Gewünschtes Geschlecht für die Berufsbezeichnungen.

            🇬🇧 Desired gender for occupation descriptions.
        - name: eventDate
          in: query
          required: true
          description: |
            🇩🇪 Das Datum des Unfall-Ereignisses. Wenn das aktuelle Tagesdatum verwendet wird, muss die Schnittstelle
            später erneut mit dem Ereignis-Datum des Schadens aufgerufen werden, insbesondere bei einem Jahreswechsel,
            um sicherzustellen, dass die in der Schadenmeldung referenzierten Objekte zum Ereignis-Datum gültig sind.
            **Einschränkung:** Datum muss <= Tagesdatum sein und nicht weiter zurück als das vorhergehende Kalenderjahr.

            🇬🇧 The event date. If the current date is used, the API should later be called again
            with the accident event date, particularly if a year change occurs in between,
            to ensure objects referenced in the accident report are valid at the event date.
            **Restriction:** The date must be <= today's date and no earlier than the previous calendar year.
          schema:
            type: string
            format: date
        - name: customerID
          in: query
          required: false
          description: |
            🇩🇪 Die Suva-Kundennummer (z.B. 8-01747-90000).

            🇬🇧 Suva customer ID (e.g., 8-01747-90000).
          schema:
            type: string
        - $ref: "#/components/parameters/X-Client-Vendor"
        - $ref: "#/components/parameters/X-Client-Name"
        - $ref: "#/components/parameters/X-Client-Version"
      responses:
        200:
          description: |
            🇩🇪 Gefilterte Liste von Subnummern.

            🇬🇧 Filtered list of subnumbers.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/SubnummerFiltered"
        400:
          $ref: "#/components/responses/NotAuthenticatedError"

components:
  securitySchemes:
    ApiKeyAuth:
      description: |
        🇩🇪 Authentifizierung über Bearer-Token - siehe OAuth-Beispiele auf https://github.com/suva-ch/risk-api-demo-python/tree/main

        🇬🇧 Authentication via Bearer Token - see OAuth examples at https://github.com/suva-ch/risk-api-demo-python/tree/main
      type: http
      scheme: bearer

  parameters:
    X-Client-Vendor:
      name: X-Client-Vendor
      in: header
      description: |
        🇩🇪 Name des Herstellers der Client-Anwendung.

        🇬🇧 Name of the vendor responsible for the client application.
      required: false
      schema:
        type: string
      example: "Acme Corporation"
    X-Client-Name:
      name: X-Client-Name
      in: header
      description: |
        🇩🇪 Produkt-Name der Client-Anwendung.

        🇬🇧 Product name of the client application.
      required: false
      schema:
        type: string
      example: "PayrollPro"
    X-Client-Version:
      name: X-Client-Version
      in: header
      description: |
        🇩🇪 Version der Anwendung.

        🇬🇧 Version of the application.
      required: false
      schema:
        type: string
      example: "2.5"
      
  schemas:
    Subnummer:
      description: |
        🇩🇪 Datenstruktur einer Subnummer.

        🇬🇧 Data structure of a subnumber.
      type: object
      properties:
        subnumberCode:
          type: string
          description: |
            🇩🇪 Subnummer als 2-stellige Zahl.

            🇬🇧 Subnumber as a 2-digit code.
          example: "01"
          pattern: "^\\d{2}$"
        description:
          type: string
          description: |
            🇩🇪 Beschreibung der Subnummer in der Sprache des Kunden (keine Mehrsprachigkeit verfügbar).
            Bei anonymem Zugriff werden diese Daten nicht geliefert.

            🇬🇧 Description of the subnumber in the customer's language (multilingualism not available).
            This data is not available for anonymous access.
        premiumModel:
          type: string
          enum: [UVG_CLASSIC, UVG_OCCUPATION_CODES]
          description: |
            🇩🇪 Premien-Modell der Subnummer.
            UVG_CLASSIC: klassisch UVG mit Risiko-Ermittlung auf Basis von Betriebsbeschreibung
            UVG_OCCUPATION_CODES: UVG mit Risiko-Ermittlung auf Basis von Berufscodes

            🇬🇧 Premium Model of subnumber.
            UVG_CLASSIC: classic UVG with risk identification based on description of operation
            UVG_OCCUPATION_CODES: UVG with risk identification based on occupation codes
        businessUnits:
          type: array
          description: |
            🇩🇪 Enthält Betriebsteile, wenn das Prämienmodell `UVG_CLASSIC` ist.

            🇬🇧 Contains business parts if the premium model is `UVG_CLASSIC`.
          items:
            $ref: "#/components/schemas/BusinessUnit"
        occupationCodes:
          type: array
          description: |
            🇩🇪 Enthält Berufscodes, wenn das Prämienmodell `UVG_OCCUPATION_CODES` ist.

            🇬🇧 Contains occupation codes if the premium model is `UVG_OCCUPATION_CODES`.
          items:
            $ref: "#/components/schemas/OccupationCode"
      required:
        - subnumberCode
        - premiumModel

    SubnummerFiltered:
      description: |
        🇩🇪 Gefilterte Datenstruktur einer Subnummer mit sprachspezifischen Beschreibungen.

        🇬🇧 Filtered data structure of a subnumber with language-specific descriptions.
      type: object
      properties:
        subnumberCode:
          type: string
          description: |
            🇩🇪 Subnummer als 2-stellige Zahl.

            🇬🇧 Subnumber as a 2-digit code.
          example: "01"
          pattern: "^\\d{2}$"
        description:
          type: string
        premiumModel:
          type: string
          enum: [UVG_CLASSIC, UVG_OCCUPATION_CODES]
        businessUnits:
          type: array
          items:
            $ref: "#/components/schemas/BusinessUnitFiltered"
        occupationCodes:
          type: array
          items:
            $ref: "#/components/schemas/OccupationCodeFiltered"
      required:
        - subnumberCode
        - premiumModel

    BusinessUnit:
      description: |
        🇩🇪 Ein Betriebsteil innerhalb einer Subnummer.

        🇬🇧 A business part within a subnumber.
      type: object
      properties:
        businessUnitCode:
          type: string
          description: |
            🇩🇪 Buchstabe zur Identifikation des Betriebsteils.

            🇬🇧 Letter identifier for the business part.
          example: "A"
          pattern: "^[A-Z]$"
        description:
          type: string
          description: |
            🇩🇪 Textbeschreibung des Betriebsteils in der Sprache des Kunden (keine Mehrsprachigkeit verfügbar).
            Bei anonymem Zugriff werden diese Daten nicht geliefert.

            🇬🇧 Text description of the business part in the customer's language (multilingualism not available).
            This data is not available for anonymous access.
      required:
        - businessUnitCode

    BusinessUnitFiltered:
      type: object
      properties:
        businessUnitCode:
          type: string
          example: "A"
          pattern: "^[A-Z]$"
        description:
          type: string
      required:
        - businessUnitCode

    OccupationCode:
      description: |
        🇩🇪 Details zu einem Berufscode.

        🇬🇧 Details of an occupation code.
      type: object
      properties:
        occupationCodeNr1:
          type: string
          description: |
            🇩🇪 Berufscode-Nummer 1 - vom Kunden vergeben

            🇬🇧 Occupation code number 1 - assigned by the customer.
        occupationCodeNr2:
          type: string
          description: |
            🇩🇪 Berufscode-Nummer 2 - vom Kunden vergeben

            🇬🇧 Occupation code number 2 - assigned by the customer.
        suvaOccupationCodeId:
          type: string
          format: uuid
          description: |
            🇩🇪 Eindeutige ID des Suva-Berufscodes.

            🇬🇧 Unique ID of the Suva occupation code.

        IscoOccupationTypeId:
          description: |
            🇩🇪 5-Stellige Nummer für Berufsarten aus der Schweizer Berufsnomenklatur.
            z.B. "71140" für "Eisenleger"

            🇬🇧 5-digit code for occupations from the Swiss occupational nomenclature.
            e.G. "71140" for "Reinforcing iron and rebar worker"
          type: integer
          example: 71140

        active:
          type: boolean
          description: |
            🇩🇪 Gibt an, ob der Berufscode aktiv ist.

            🇬🇧 Indicates if the occupation code is active.
        descriptions:
          type: array
          description: |
            🇩🇪 Sprach- und geschlechtsspezifische Berufsbezeichnung.

            🇬🇧 Language- and gender-specific occupation description.
          items:
            $ref: "#/components/schemas/OccupationDescription"
        businessUnitCode:
          type: string
          description: |
            🇩🇪 Buchstabe des zugehörigen Betriebsteils für Schadenmeldung

            🇬🇧 Letter of the associated business part for accident reporting.
          example: "A"
          pattern: "^[A-Z]$"
      required:
        - suvaOccupationCodeId
        - IscoOccupationTypeId
        - active
        - businessUnitCode

    OccupationCodeFiltered:
      type: object
      properties:
        occupationCodeNr1:
          type: string
        occupationCodeNr2:
          type: string
        suvaOccupationCodeId:
          type: string
          format: uuid
        IscoOccupationTypeId:
          type: integer
        active:
          type: boolean
        description:
          type: string
        businessUnitCode:
          type: string
          example: "A"
          pattern: "^[A-Z]$"
      required:
        - suvaOccupationCodeId
        - IscoOccupationTypeId
        - active
        - businessUnitCode

    OccupationDescription:
      description: |
        🇩🇪 Sprach- und geschlechtsspezifische Berufsbezeichnung.

        🇬🇧 Language- and gender-specific occupation description.
      type: object
      properties:
        language:
          type: string
          description: |
            🇩🇪 Sprache des Wertes.

            🇬🇧 Language of the value.
          enum: [de, fr, it, en]

        gender:
              $ref: "#/components/schemas/Gender"

        value:
          type: string
          description: |
            🇩🇪 Text in der entsprechenden Sprache.

            🇬🇧 Text in the corresponding language.
      required:
      - language
      - gender
      - value


    Gender:
      description: |
        🇩🇪  Geschlecht
        
        🇬🇧 Gender
      type: string
      enum: [ female, genderless, male ]


    Error:
      description: |
        🇩🇪 Fehlermeldung

        🇬🇧 Error message.
      properties:
        message:
          description: |
            🇩🇪 Die in englischer Sprache gelieferte Fehlermeldung. Beispiel: 'Berufscode-Liste for Partner-Nr. '9999999999' not found'.

            🇬🇧 Error message provided in English. Example: 'Occupation code list for partner number '9999999999' not found.'
          type: string
        id:
          description: |
            🇩🇪 Eindeutige ID der Fehlermeldung. Beispiel: Zwei Fehlermeldungen 'Berufscode-Liste for Partner-Nr. '9999999999' not found' haben unterschiedliche ID's.

            🇬🇧 Unique ID of the error message. Example: Two error messages 'Occupation code list for partner number '9999999999' not found' have different IDs.
          type: string
        key:
          description: |
            🇩🇪 Key der Fehlermeldung. Beispiel: Zwei Fehlermeldungen 'Berufscode-Liste for Partner-Nr. '9999999999' not found' haben denselben Key.

            🇬🇧 Key of the error message. Example: Two error messages 'Occupation code list for partner number '9999999999' not found' have the same key.
          type: string
        args:
          description: |
            🇩🇪 Argumente für die Aufbereitung einer Fehlermeldung. Zum Beispiel: '9999999999'

            🇬🇧 Arguments for formatting an error message. For example: '9999999999'
          type: array
          items:
            type: string
      required:
        - message
        - id
        - key

  responses:
    NotAuthenticatedError:
      description: |
        🇩🇪 Keine gültigen Authentifizierungsdaten für die angeforderte Ressource vorhanden.

        🇬🇧 No valid authentication data available for the requested resource.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
