openapi: 3.0.0
info:
  version: 1.0.0-FIXME
  title: Policendaten Schadenmeldung API
  description: |
    # de
    Diese API liefert Policendaten basierend auf dem Ereignis-Datum für eine Schadenmeldung.

    # en
    This API provides policy data based on the event date for an accident report.
  license:
    name: Apache License 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: FIXME

paths:
  /policy:
    get:
      description: |
        # de
        Liefert eine Liste von Subnummern basierend auf dem Ereignis-Datum und optional der Suva KundenNr. 
        Falls keine KundenNr angegeben wird, wird die Authentifizierung zur Identifikation des Kunden verwendet.

        # en
        Provides a list of subnumbers based on the event date and optionally the Suva customer ID. 
        If no customer ID is specified, authentication will identify the customer.
      tags:
        - Policendaten
      operationId: getPolicy
      parameters:
        - name: eventDate
          in: query
          required: true
          description: |
            # de
            Das Datum des Unfall-Ereignisses. Wenn das aktuelle Tagesdatum verwendet wird, muss die Schnittstelle
            später erneut mit dem Ereignis-Datum des Schadens aufgerufen werden, insbesondere bei einem Jahreswechsel,
            um sicherzustellen, dass die in der Schadenmeldung referenzierten Objekte zum Ereignis-Datum gültig sind.

            # en
            The event date. If the current date is used, the API should later be called again
            with the accident event date, particularly if a year change occurs in between,
            to ensure objects referenced in the accident report are valid at the event date.
          schema:
            type: string
            format: date
        - name: customerID
          in: query
          required: false
          description: |
            # de
            Die Suva-Kundennummer (z.B. 8-01747-90000).

            # en
            Suva customer ID (e.g., 8-01747-90000).
          schema:
            type: string
        - $ref: "#/components/parameters/X-Client-Vendor"
        - $ref: "#/components/parameters/X-Client-Name"
        - $ref: "#/components/parameters/X-Client-Version"
      security:
        # de
        # Entweder mit API-Key oder anonym - im Fall von anonymem Zugriff werden nicht alle Daten geliefert.
        # 
        # en
        # Access can be anonymous, but API-key usage is recommended as anonymous access may limit data retrieval.
        - ApiKeyAuth: [] 
      responses:
        200:
          description: |
            # de
            Liste von Subnummern der Police.

            # en
            List of policy subnumbers.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Subnummer"
        401:
          description: |
            # de
            Ungültige Authentifizierung oder Daten mit der Authentifizierung nicht zugänglich.

            # en
            Invalid authentication or inaccessible data for the provided authentication.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        400:
          description: |
            # de
            Anfrage konnte nicht verarbeitet werden.

            # en
            The request could not be processed due to an error.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  securitySchemes:
    ApiKeyAuth:
      description: |
        # de
        Kunden-spezifischer API-Key aus dem mySuva-Kundenportal

        # en
        Customer-specific API key provided through the mySuva customer portal.
      type: apiKey
      in: header
      name: X-suva-api-key

  parameters:
    X-Client-Vendor:
      name: X-Client-Vendor
      in: header
      description: |
        # de
        Name des Herstellers der Client-Anwendung.

        # en
        Name of the vendor responsible for the client application.
      required: false
      schema:
        type: string
      example: "Acme Corporation"
    X-Client-Name:
      name: X-Client-Name
      in: header
      description: |
        # de
        Produkt-Name der Client-Anwendung.

        # en
        Product name of the client application.
      required: false
      schema:
        type: string
      example: "PayrollPro"
    X-Client-Version:
      name: X-Client-Version
      in: header
      description: |
        # de
        Version der Anwendung.

        # en
        Version of the application.
      required: false
      schema:
        type: string
      example: "2.5"
      
  schemas:
    Subnummer:
      description: |
        # de          
        Datenstruktur einer Subnummer.

        # en
        Data structure of a subnumber.
      type: object
      properties:
        subnumberCode:
          type: string
          description: |
            # de
            Subnummer als 2-stellige Zahl.
            # en
            Subnumber as a 2-digit code.
          example: "01"
          pattern: "^\\d{2}$"
        description:
          type: string
          description: |
            # de
            Beschreibung der Subnummer in der Sprache des Kunden (keine Mehrsprachigkeit verfügbar).
            Bei anonymem Zugriff werden diese Daten nicht geliefert.

            # en
            Description of the subnumber in the customer's language (multilingualism not available).
            This data is not available for anonymous access.
        premiumModel:
          type: string
          enum: [UVG_CLASSIC, UVG_OCCUPATION_CODES]
          description: |
            # de
            Premien-Modell der Subnummer.
            UVG_CLASSIC: klassisch UVG mit Risiko-Ermittlung auf Basis von Betriebsbeschreibung
            UVG_OCCUPATION_CODES: UVG mit Risiko-Ermittlung auf Basis von Berufscodes

            # en
            Premium Model of subnumber.
            UVG_CLASSIC: classic UVG with risk identification based on description of operation
            UVG_OCCUPATION_CODES: UVG with risk identification based on occupation codes
        businessUnits:
          type: array
          description: |
            # de
            Enthält Betriebsteile, wenn das Prämienmodell `UVG_CLASSIC` ist.

            # en
            Contains business parts if the premium model is `UVG_CLASSIC`.
          items:
            $ref: "#/components/schemas/BusinessUnit"
        occupationCodes:
          type: array
          description: |
            # de
            Enthält Berufscodes, wenn das Prämienmodell `UVG_OCCUPATION_CODES` ist.

            # en
            Contains occupation codes if the premium model is `UVG_OCCUPATION_CODES`.
          items:
            $ref: "#/components/schemas/OccupationCode"

    BusinessUnit:
      description: |
        # de
        Ein Betriebsteil innerhalb einer Subnummer.

        # en
        A business part within a subnumber.
      type: object
      properties:
        businessUnitCode:
          type: string
          description: |
            # de
            Buchstabe zur Identifikation des Betriebsteils.

            # en
            Letter identifier for the business part.
          example: "A"
          pattern: "^[A-Z]$"
        description:
          type: string
          description: |
            # de
            Textbeschreibung des Betriebsteils in der Sprache des Kunden (keine Mehrsprachigkeit verfügbar).
            Bei anonymem Zugriff werden diese Daten nicht geliefert.

            # en
            Text description of the business part in the customer's language (multilingualism not available).
            This data is not available for anonymous access.

    OccupationCode:
      description: |
        # de
        Details zu einem Berufscode.

        # en
        Details of an occupation code.
      type: object
      properties:
        occupationCodeNr1:
          type: string
          description: |
            # de
            Berufscode-Nummer 1 - vom Kunden vergeben

            # en
            Occupation code number 1 - assigned by the customer.
        occupationCodeNr2:
          type: string
          description: |
            # de
            Berufscode-Nummer 2 - vom Kunden vergeben

            # en
            Occupation code number 2 - assigned by the customer.
        suvaOccupationCodeId:
          type: string
          format: uuid
          description: |
            # de
            Eindeutige ID des Suva-Berufscodes.

            # en
            Unique ID of the Suva occupation code.
        active:
          type: boolean
          description: |
            # de
            Gibt an, ob der Berufscode aktiv ist.

            # en
            Indicates if the occupation code is active.
        descriptions:
          type: array
          description: |
            # de
            Mehrsprachige Beschreibung des Berufscodes.

            # en
            Multilingual description of the occupation code.
          items:
            $ref: "#/components/schemas/LocalizedValue"
        betriebsTeilLetter:
          type: string
          description: |
            # de
            Buchstabe des zugehörigen Betriebsteils für Schadenmeldung

            # en
            Letter of the associated business part for accident reporting.
          example: "A"
          pattern: "^[A-Z]$"

    LocalizedValue:
      description: |
        # de
        Ein sprachbezogener Wert.

        # en
        A language-specific value.
      type: object
      properties:
        language:
          type: string
          description: |
            # de
            Sprache des Wertes.

            # en
            Language of the value.
          enum: [de, fr, it, en]
        value:
          type: string
          description: |
            # de
            Text in der entsprechenden Sprache.

            # en
            Text in the corresponding language.

    Error:
      description: |
        # de
        Fehlermeldung

        # en
        Error message.
      properties:
        message:
          description: |
            # de
            Die in englischer Sprache gelieferte Fehlermeldung. Beispiel: 'Berufscode-Liste for Partner-Nr. '9999999999' not found'.

            # en
            Error message provided in English. Example: 'Occupation code list for partner number '9999999999' not found.'
          type: string
        id:
          description: |
            # de
            Eindeutige ID der Fehlermeldung. Beispiel: Zwei Fehlermeldungen 'Berufscode-Liste for Partner-Nr. '9999999999' not found' haben unterschiedliche ID's.

            # en
            Unique ID of the error message. Example: Two error messages 'Occupation code list for partner number '9999999999' not found' have different IDs.
          type: string
        key:
          description: |
            # de
            Key der Fehlermeldung. Beispiel: Zwei Fehlermeldungen 'Berufscode-Liste for Partner-Nr. '9999999999' not found' haben denselben Key.

            # en
            Key of the error message. Example: Two error messages 'Occupation code list for partner number '9999999999' not found' have the same key.
          type: string
        args:
          description: |
            # de
            Argumente für die Aufbereitung einer Fehlermeldung. Zum Beispiel: '9999999999'

            # en
            Arguments for formatting an error message. For example: '9999999999'
          type: array
          items:
            type: string
      required:
        - message
        - id
        - key

  responses:
    NotAuthenticatedError:
      description: |
        # de
        Keine gültigen Authentifizierungsdaten für die angeforderte Ressource vorhanden.

        # en
        No valid authentication data available for the requested resource.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
